### ISSUE TITLE
CI/CD Pipeline

### ISSUE THREAD

**Issue by Fakepng** [Fakepng/mobile-app-KMITL#2]
GitHub Action
```yaml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: my-app

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:latest .

    # Save the Docker image as a tarball
    - name: Save Docker image to file
      run: |
        docker save $IMAGE_NAME:latest > $IMAGE_NAME.tar

    # Transfer the image to the VM using SSH
    - name: Transfer Docker image to VM
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        source: "$IMAGE_NAME.tar"
        target: "/home/${{ secrets.VM_USERNAME }}/$IMAGE_NAME.tar"

    # Deploy the Docker image on the VM
    - name: Deploy Docker image on VM
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          docker load < /home/${{ secrets.VM_USERNAME }}/$IMAGE_NAME.tar
          docker stop $IMAGE_NAME || true
          docker rm $IMAGE_NAME || true
          docker run -d --name $IMAGE_NAME -p 80:80 $IMAGE_NAME:latest
          rm -f /home/${{ secrets.VM_USERNAME }}/$IMAGE_NAME.tar
```
